# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REiaoE8Q5dEfu4XQ2swjonEbalJ9LpYc
"""

!pip install streamlit
import streamlit as st

# Title of the app
st.title("Welcome to My Chatbot!")

# Description
st.write("This is a Streamlit-based chatbot application.")